In [70]:
import tensorflow as tf

In [217]:
import keras as ks

In [72]:
import pandas as pd

In [73]:
import numpy as np

In [74]:
import datetime as dt

In [75]:
import seaborn as sns

In [77]:
import sklearn as sk

In [78]:
from sklearn import preprocessing

In [79]:
from pandas_datareader import data

In [80]:
import matplotlib.pyplot as plt

In [81]:
from sklearn.preprocessing import MinMaxScaler

In [160]:
from keras.preprocessing.sequence import TimeseriesGenerator

In [82]:
data = pd.read_csv('LSTM.csv')

In [83]:
data

Facility Calendar_Day Product_Type WIP_AVG_EOL MOVES_EOL WIP_AVG_FOL  \
0        OSFER   26.07.2019  F0279D00300           2         0          24   
1        OSFER   26.07.2019  F0280D00300         109       422         102   
2        OSFER   26.07.2019  F0280E00300          76       341          66   
3        OSFER   26.07.2019  F0281D00300          26        48          27   
4        OSFER   26.07.2019  F0282D00300         117       576          24   
...        ...          ...          ...         ...       ...         ...   
63990    OSFER   17.07.2020  M8860F00020          12        48         269   
63991    OSFER   17.07.2020  M8864F00130           9         0           0   
63992    OSFER   17.07.2020  M8880N00020           0         0         168   
63993    OSFER   17.07.2020  M9463N00000           0         0           7   
63994    OSFER   17.07.2020  M9463N01000           0         0          15   

      MOVES_FOL    FF  
0           169   NaN  
1           294  4.53  
2           416   NaN  
3             0  6.43  
4           168  3.42  
...         ...   ...  
63990       243   NaN  
63991         0   NaN  
63992       202   NaN  
63993         0   NaN  
63994         4   NaN  

[63995 rows x 8 columns]

In [84]:
data.head()

Facility Calendar_Day Product_Type WIP_AVG_EOL MOVES_EOL WIP_AVG_FOL  \
0    OSFER   26.07.2019  F0279D00300           2         0          24   
1    OSFER   26.07.2019  F0280D00300         109       422         102   
2    OSFER   26.07.2019  F0280E00300          76       341          66   
3    OSFER   26.07.2019  F0281D00300          26        48          27   
4    OSFER   26.07.2019  F0282D00300         117       576          24   

  MOVES_FOL    FF  
0       169   NaN  
1       294  4.53  
2       416   NaN  
3         0  6.43  
4       168  3.42

In [85]:
type (data)

pandas.core.frame.DataFrame

In [86]:
data.tail()

Facility Calendar_Day Product_Type WIP_AVG_EOL MOVES_EOL WIP_AVG_FOL  \
63990    OSFER   17.07.2020  M8860F00020          12        48         269   
63991    OSFER   17.07.2020  M8864F00130           9         0           0   
63992    OSFER   17.07.2020  M8880N00020           0         0         168   
63993    OSFER   17.07.2020  M9463N00000           0         0           7   
63994    OSFER   17.07.2020  M9463N01000           0         0          15   

      MOVES_FOL  FF  
63990       243 NaN  
63991         0 NaN  
63992       202 NaN  
63993         0 NaN  
63994         4 NaN

In [155]:
plt.figure(figsize=(20,10), dpi=1000)
plt.plot(data1, color='red', linewidth=3, markersize=10)
plt.xlabel('Index')
plt.ylabel('FF')
plt.xticks([0, 1000, 1976, 5000, 10000, 15000, 20000, 25000, 30000, 32846, 35000, 40000, 45000, 48500, 50000, 52153, 55000, 60000])
plt.yticks([0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000])

([<matplotlib.axis.YTick at 0x61e1b74648>,
 <a list of 13 Text major ticklabel objects>)

In [87]:
from keras.models import Sequential

In [88]:
from keras.layers.recurrent import LSTM

In [89]:
from keras.layers.core import Dense, Activation, Dropout

In [91]:
from sklearn.metrics import mean_squared_error

In [92]:
from sklearn.utils import Sequence

In [177]:
from tensorflow.keras import layers
from keras.layers import InputLayer

In [173]:
from tensorflow.keras import activations

In [93]:
data1=data.reset_index()['FF']

In [94]:
data1.shape

(63995,)

In [95]:
data1

0         NaN
1        4.53
2         NaN
3        6.43
4        3.42
         ... 
63990     NaN
63991     NaN
63992     NaN
63993     NaN
63994     NaN
Name: FF, Length: 63995, dtype: float64

In [139]:
data.isnull().head()

Facility  Calendar_Day  Product_Type  WIP_AVG_EOL  MOVES_EOL  WIP_AVG_FOL  \
0     False         False         False        False      False        False   
1     False         False         False        False      False        False   
2     False         False         False        False      False        False   
3     False         False         False        False      False        False   
4     False         False         False        False      False        False   

   MOVES_FOL     FF  
0      False   True  
1      False  False  
2      False   True  
3      False  False  
4      False  False

In [138]:
data[data['FF'].isnull()]

Facility Calendar_Day Product_Type WIP_AVG_EOL MOVES_EOL WIP_AVG_FOL  \
0        OSFER   26.07.2019  F0279D00300           2         0          24   
2        OSFER   26.07.2019  F0280E00300          76       341          66   
5        OSFER   26.07.2019  F0282E00300          77       100          35   
8        OSFER   26.07.2019  F0292E00300          41        81          15   
9        OSFER   26.07.2019  F0347C00300          41       158           0   
...        ...          ...          ...         ...       ...         ...   
63990    OSFER   17.07.2020  M8860F00020          12        48         269   
63991    OSFER   17.07.2020  M8864F00130           9         0           0   
63992    OSFER   17.07.2020  M8880N00020           0         0         168   
63993    OSFER   17.07.2020  M9463N00000           0         0           7   
63994    OSFER   17.07.2020  M9463N01000           0         0          15   

      MOVES_FOL  FF  
0           169 NaN  
2           416 NaN  
5           153 NaN  
8            75 NaN  
9             0 NaN  
...         ...  ..  
63990       243 NaN  
63991         0 NaN  
63992       202 NaN  
63993         0 NaN  
63994         4 NaN  

[56284 rows x 8 columns]

In [97]:
scaler=MinMaxScaler(feature_range=(0,1))

In [98]:
data1=scaler.fit_transform(np.array(data1).reshape(-1,1))

In [107]:
data.isnull().sum()

Facility            0
Calendar_Day        0
Product_Type        0
WIP_AVG_EOL         0
MOVES_EOL           0
WIP_AVG_FOL         0
MOVES_FOL           0
FF              56284
dtype: int64

In [141]:
modifiedDataset=data.fillna("--")

In [142]:
modifiedDataset

Facility Calendar_Day Product_Type WIP_AVG_EOL MOVES_EOL WIP_AVG_FOL  \
0        OSFER   26.07.2019  F0279D00300           2         0          24   
1        OSFER   26.07.2019  F0280D00300         109       422         102   
2        OSFER   26.07.2019  F0280E00300          76       341          66   
3        OSFER   26.07.2019  F0281D00300          26        48          27   
4        OSFER   26.07.2019  F0282D00300         117       576          24   
...        ...          ...          ...         ...       ...         ...   
63990    OSFER   17.07.2020  M8860F00020          12        48         269   
63991    OSFER   17.07.2020  M8864F00130           9         0           0   
63992    OSFER   17.07.2020  M8880N00020           0         0         168   
63993    OSFER   17.07.2020  M9463N00000           0         0           7   
63994    OSFER   17.07.2020  M9463N01000           0         0          15   

      MOVES_FOL    FF  
0           169    --  
1           294  4.53  
2           416    --  
3             0  6.43  
4           168  3.42  
...         ...   ...  
63990       243    --  
63991         0    --  
63992       202    --  
63993         0    --  
63994         4    --  

[63995 rows x 8 columns]

In [144]:
from sklearn.model_selection import train_test_split

In [145]:
x=np.asarray(data[['Calendar_Day', 'Product_Type', 'WIP_AVG_EOL', 'MOVES_EOL', 'WIP_AVG_FOL', 'MOVES_FOL']])
y=np.asarray(data['FF'])

In [146]:
x.ndim

2

In [147]:
y.ndim

1

In [148]:
x.shape

(63995, 6)

In [149]:
y.shape

(63995,)

In [150]:
x=np.random.rand(63995,6)

In [151]:
x

array([[0.6430741 , 0.60580172, 0.98683942, 0.88464922, 0.7978675 ,
        0.69889577],
       [0.14710023, 0.96930357, 0.30178023, 0.6916036 , 0.18878834,
        0.95281748],
       [0.01920387, 0.61534162, 0.88472212, 0.82624492, 0.75890856,
        0.81563031],
       ...,
       [0.50992192, 0.78803077, 0.2500096 , 0.2164368 , 0.55537456,
        0.91517534],
       [0.51529138, 0.40477725, 0.52373044, 0.02317871, 0.84638486,
        0.57357946],
       [0.77521758, 0.07522421, 0.62342958, 0.93776657, 0.13020879,
        0.13068898]])

In [152]:
y=np.random.rand(63995,)

In [153]:
y

array([0.09014738, 0.2770631 , 0.29286301, ..., 0.5033402 , 0.15239531,
       0.99972296])

In [51]:
x.size

383970

In [154]:
y.size

63995

In [156]:
y.shape

(63995,)

In [159]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.15, random_state=1) 

In [54]:
x_train = x_train.reshape((-1, 326370, 1))
y_train = y_train.reshape((-1, 54395))

In [199]:
X = data.values
train_size = int(len(X) * 0.85)
train, test = X[0:train_size], X[train_size:len(X)]
print('Observations: %d' % (len(X)))
print('Training Observations: %d' % (len(train)))
print('Testing Observations: %d' % (len(test)))

Observations: 63995
Training Observations: 54395
Testing Observations: 9600


In [115]:
data.isnull().sum()

Facility            0
Calendar_Day        0
Product_Type        0
WIP_AVG_EOL         0
MOVES_EOL           0
WIP_AVG_FOL         0
MOVES_FOL           0
FF              56284
dtype: int64

In [209]:
look_back = 3
train_data_gen = TimeseriesGenerator(x_train, y_train,length=look_back, sampling_rate=1,stride=1,batch_size=3)
test_data_gen = TimeseriesGenerator(x_test, y_test,length=look_back, sampling_rate=1,stride=1,batch_size=1)

In [180]:
model = Sequential()
model.add(LSTM(3, input_shape=(look_back, 6)))
model.add(Dense(1))
model_lstm.add(activation = 'relu')
model.compile(loss='mean_squared_error', optimizer='adam')
history = model.fit_generator(train_data_gen, epochs=100).history

Epoch 1/100
15411/15411 [==============================] - 62s 4ms/step - loss: 0.0848
Epoch 2/100
15411/15411 [==============================] - 62s 4ms/step - loss: 0.0842
Epoch 3/100
15411/15411 [==============================] - 61s 4ms/step - loss: 0.0842
Epoch 4/100
15411/15411 [==============================] - 63s 4ms/step - loss: 0.0841
Epoch 5/100
15411/15411 [==============================] - ETA: 0s - loss: 0.084 - 63s 4ms/step - loss: 0.0841
Epoch 6/100
15411/15411 [==============================] - 63s 4ms/step - loss: 0.0841
Epoch 7/100
15411/15411 [==============================] - ETA: 0s - loss: 0.084 - 63s 4ms/step - loss: 0.0841
Epoch 8/100
15411/15411 [==============================] - 63s 4ms/step - loss: 0.0841
Epoch 9/100
15411/15411 [==============================] - 63s 4ms/step - loss: 0.0841
Epoch 10/100
15411/15411 [==============================] - 63s 4ms/step - loss: 0.0840
Epoch 11/100
15411/15411 [==============================] - 63s 4ms/step - loss: 

In [210]:
model.evaluate_generator(test_data_gen)
trainPredict = model.predict_generator(train_data_gen)
testPredict = model.predict_generator(test_data_gen)

In [211]:
trainPredict = model.predict_generator(train_data_gen)
trainPredict.shape

(46232, 1)

In [216]:
testPredict = model.predict_generator(test_data_gen)
testPredict.shape

(9597, 1)

In [213]:
trainPredict = scaler.inverse_transform(trainPredict)
testPredict = scaler.inverse_transform(testPredict)

In [214]:
testPredict

array([[2727.2205],
       [2891.121 ],
       [2846.9612],
       ...,
       [2725.16  ],
       [2914.6736],
       [2778.018 ]], dtype=float32)

In [215]:
trainPredict

array([[2728.0276],
       [2797.1802],
       [2642.6516],
       ...,
       [2883.891 ],
       [2762.7935],
       [2753.799 ]], dtype=float32)